routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::get('/post/{id}', 'PostsController@show');

Route::resource('/posts', 'PostsController');


















Route::get('/about', function (){

	return (view("about"));

});

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable = ['user_id', 'description', 'post_id'];

    public function post(){

        return $this->belongsTo('App\Post');

    }

    public function user(){

        return $this->belongsTo('App\User', 'user_id');

    }

}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    public function comments(){

    	return $this->hasMany('App\Comment');

    }

    public function user(){

    return $this->belongsTo('App\User', 'user_id');

	}
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'birth_date', 'gen', 'address', 'solved_count',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function posts(){

        return $this->hasMany('App\Post');
        
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return redirect('/posts');
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Post;

use App\Comment;

class PostsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::all();

        return view('posts', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $comm = new Comment;

        $comm->description = $request->description;

        $comm->user_id = $request->user_id;

        $comm->post_id = $request->post_id;

        $comm->save();

        return redirect("/posts/".$request->post_id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::findOrFail($id);

        $comments = $post->comments;

        return view('post', compact('post', 'comments'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/about.blade.php
<!DOCTYPE html>
<html>
<head>
<link rel=icon href=images/head_logo.png sizes="16x16" type="image/png">
<link href="https://fonts.googleapis.com/css?family=Slabo+27px" rel="stylesheet">
<style>

h1 {
    text-align: center;
    text-transform: uppercase;
    color: #A8CF45;
}

h2 {
    text-align: center;
    text-transform: uppercase;
    color: #34F4EE;
}
body{padding:0; margin: 0;
font-family:'Slabo 27px', "Times New Roman", Times, serif;
}
.navbar{
	list-style-type: none;
	top: 0;

	margin: 0;
	padding: 0;

	position: static;
	background-color: ;
	border-radius: 0px 0px 5px 5px;
}

.float-right{
	float: right;
}

.float-left{
	float: left;
}

.navbar-content{
	display: inline-block;
	color: white;
	text-align: center;
	padding: 15px;
	text-decoration: none;
	font-family:'Slabo 27px', "Times New Roman", Times, serif;
}

.navbar-content.active{
	background-color: #A8CF45;
}

.navbar-content:hover:not(.active){
	background-color: #656565;
}

 ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
   
}

li {
    float: left;
}


.logo img {
    width: 45%;
    height: auto;
    display: block;
  
    margin-top: auto;
}


body { background-attachment: fixed; background-repeat: no-repeat;
	background-size: cover ; width: 100%;
    height: auto;
 }


div.text1 {
  
  
    text-align: justify;
color: #DCDCC6;
font-size: 25px;
 text-indent: 50px;
    letter-spacing: 3px;

    padding-right: 150px;
    padding-left: 150px;
} 


 footer {
    padding: 1em;
    color: #A8CF45  ;
   
    clear: left; 
    text-align: center;
}


li c {
    display: block;
    color: white;
    text-align: center;
    padding: 16px;
    text-decoration: none;
    font-size: 20px;
    color: #34F4EE;
}


}

</style>
</head>
<body background="images/back3.jpg">
<div  class="logo" style="margin:20px 0px 20px 20px;">
<a href="{{ url('/') }}">
<img src="images/logo-Klove.png" >
</a>
</div>

 <div style="text-align:center;
 background-image: url(images/back2.png);
 background-repeat:no-repeat;
 opacity:0.9;
 background-attachment: fixed;
 width:auto; height:500px;" id="mainpage" align="center";>
<br>
 <h1>About Us !</h1>

<div class="text1"><p>&nbsp&nbspWe, Helper Society in partnership with KLOVE and Air1, elaborated a method based on easy and fast communication. We are a modest group of people that encourage neighbors to cummunicate,promote mutual help and tolerance. Neighbors beeing a symbol of support.</p></div>

<br><br>


<ul>
	<h2>Members:</h2><br>
	<li><c>&nbsp&nbsp&nbsp&nbsp&nbsp&nbspBîrca Vladimir</c></li>
	<li><c>Constantin Cuciurcă</c></li>
	<li><c>Țurcanu Mihai</c></li>
	<li><c>Pistol Adrian</c></li>
	<li><c>Popa Roman</c></li>
	<li><c>Burac Adrian</c></li>
	<li><c>Delinschi Cristian</c></li>
	<li><c>Farras Taimoor</c></li>
</ul>

    </div>


<footer> 
<a href="http://www.klove.com/"><img src="images/klovelogo.png" style="padding:20px; width:320px;height:228px;"></a>
<a href="http://www.air1.com/"><img src="images/airone.png" style="padding:20px;  width:400px;height:100px;">
<a href="https://indigitous.org/"><img src="images/indigitous.png" style=" padding:20px; width:320px;height:228px;">
</footer>




</body>
</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
    <head>
         <title>Evricommunity</title>
         <link rel=icon href=images/head_logo.png sizes="16x16" type="image/png">
        <meta charset="utf-8">
        <link rel="stylesheet" href="/css/signup.css" type="text/css">
        <meta name="csrf-token" content="{{ csrf_token() }}">
@yield('includes')
    </head>
    <body>
        <div class="stretchedToMargin">
            <ul class="navbar">
                <li class="float-left"><a href="#" class="navbar-content">&nbsp</a></li>
                <li class="float-left" class="navbar-content"><a href="{{ url('/') }}">Home</a></li>
                @if (Auth::guest())
                            <li><a href="{{ url('/login') }}">Login</a></li>
                        @else
                            <li><a href="#" >{{ Auth::user()->name }} </a></li>
                                    <li>
                                        <a href="{{ url('/logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                        @endif
                <li class="float-right" class="navbar-content"><a href="faq.html">Q&A</a></li>
                <li class="float-right" class="navbar-content"><a href="{{ url('/about') }}">About us</a></li>
                <li class="float-right" class="navbar-content"><a href="{{ url('/posts') }}">Forum</a></li>
            </ul>

 @yield('content')
</div>
</body>
</html>

resources/views/post.blade.php
@extends('layouts.app')

@section('content')

<div class="bwrapsite-content" id="bwrapcontent" >



  <div class="post-outer">
      <article class="post hentry">
        <header class="entry-header">
          <h2 class="post-title entry-title">
           {{$post->subject}}
          </h2>
        </header>
        <div class="post-header-line-1">
        </div>
        <div class="post-body entry-content">
          <div>
            <img src="/images/back3.jpg" class="pbtthumbimg">
            <div>
            {{ $post->description }}
            </div>
          </div>
          <div style="clear: both;"></div>
        </div>
        <footer class="nbtentry-meta">
         <div class="comments" id="comments">
<a name="comments"></a>
<h4>comments:</h4>

<table>
@foreach ($comments as $comment)
	<tr style="min-height:40px;">
		<td width="20%">{{ $comment->user->name }}</td>
		<td>{{ $comment->description }}</td>
	</tr>
@endforeach
</table>



<div class="comment-form">
 <ul class="social-icons">
        <li><a href="http://www.facebook.com/sharer/sharer.php?u=evricommunity.com" class="social-icon"> <i class="fa fa-facebook"></i></a></li>
        <li><a href="https://twitter.com/intent/tweet?text={{ $post->description }}&url=evricommunity.com&via=TWITTER-HANDLER" class="social-icon"> <i class="fa fa-twitter"></i></a></li>

    </ul>

<form action="/posts" method="POST" name="commentForm" id="commentForm" accept-charset="utf-8">
{{ csrf_field() }}
<div id="commentsHolder">
<div class="commentBodyContainer">
<textarea name="description" rows="4" cols="50" id="commentBodyField" placeholder="Enter your comment..."></textarea>
<br>
</div>
<input type="hidden" name="user_id" value="{{ $post->user->id }}">
<input type="hidden" name="post_id" value="{{ $post->id }}">

<div id="identityControlsHolder" class="identity-type-CURRENT">
<div class="loggedInAvatar">
<div class="avatar-image-container avatar-stock">
</div>
</div>

</div>
</div>


<input type="submit" id="postCommentSubmit" name="postCommentSubmit" value="Publish">
<span id="empty-error"></span><span id="body-error">
<ul>
    @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
    @endforeach
</ul>
</span>
</form>

</div>

        </footer>
      </article>
    </div>
</div>

@endsection


@section('includes')
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" type="text/css" href="/css/post.css">
  <link rel="stylesheet" type="text/css" href="https://www.blogger.com/static/v1/v-css/2218177523-cmtfp.css">
  <style type="text/css">
.pbtthumbimg {

width:auto;
height:auto;
}
.bwrapsite-content {
    margin: 81px auto 0;
    max-width: none;
}
#commentsHolder {
    padding: 0;
}
button, input[type="button"]{
	padding: 0;
}
#postCommentSubmit {
    height: 30px;
    padding: 6px;
    border-radius: 4px;
    }
.comments table{
	text-transform: none;
}
 a:visited{
      color: #fff;
     }

 @import url(http://fonts.googleapis.com/css?family=Lato);
@import url(https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.css);


social-icon {

    color: #fff;
}
ul.social-icons {
   text-align:right;	
}
.social-icons li {
    display: block;
   
}
.social-icons a {
    color: #fff;
    text-decoration: none;
}
.fa-facebook {
    padding:10px 14px;
    -o-transition:.5s;
    -ms-transition:.5s;
    -moz-transition:.5s;
    -webkit-transition:.5s;
    transition: .5s;
	background-color:#000;
    
}
.fa-facebook:hover {
    background-color: #3d5b99;
}
.fa-twitter {
    padding:10px 11px;
    -o-transition:.5s;
    -ms-transition:.5s;
    -moz-transition:.5s;
    -webkit-transition:.5s;
    transition: .5s;
background-color:#000;
    
}
.fa-twitter:hover {
    background-color: #00aced;
}
  </style>
@endsection

resources/views/posts.blade.php
@extends('layouts.app')

@section('content')

@foreach ($posts as $post)

<div class="bwrapsite-content" id="bwrapcontent" >
  <div class="post-outer">
      <article class="post hentry">
        <header class="entry-header">
          <h2 class="post-title entry-title">
            {{ $post->subject }}
          </h2>
        </header>
        <div class="post-header-line-1">
        </div>
        <div class="post-body entry-content">
          <div>
            <img src="http://3.bp.blogspot.com/-xUiI8Gt_QyM/VmgGaFQcp3I/AAAAAAAAIrY/pmC0lS28CWI/s1600/btemplates-aquarium-by-francisco-oliveros.jpg" class="pbtthumbimg">
            <div>
            {{ $post->description }} 
            </div>
          </div>
          <div style="float:right;padding-right:10px;margin-top:10px;">
            <a class="nbtmore-link" style="color:#111;" href="{{ route('posts.show', $post->id) }}">Read More</a>
          </div>
          <div style="clear: both;"></div>
        </div>
        <footer class="nbtentry-meta">
          <span >
            <i class="fa fa-clock-o" aria-hidden="true"></i>
          {{ $post->created_at }}
          </span>
          <span class="nbtbyline">
            <span>
              <a href="#" rel="author" title="author profile">
                {{ $post->user->name }}
              </a>
            </span>
          </span>
          <span class="nbttags-links">
            <a href="http://sorbet2-btemplates.blogspot.md/search/label/Blogger" rel="tag">
            Blogger
            </a>, 
            <a href="http://sorbet2-btemplates.blogspot.md/search/label/Images" rel="tag">
            Images
            </a>,
            <a href="http://sorbet2-btemplates.blogspot.md/search/label/Tag" rel="tag">
            Tag
            </a>
          </span>
          <span class="nbtcomments-link">
            <a style="color: #9ba2af;" href="{{ route('posts.show', $post->id) }}">
            {{ $post->category_id }} comments
            </a>
          </span>
        </footer>
      </article>
    </div>
</div>

@endforeach

@endsection


@section('includes')
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" type="text/css" href="/css/post.css">
  <style type="text/css">
.stretchedToMargin {
     bottom: auto;
   }
     a:visited{
      color: #fff;
     }
  </style>
@endsection